"""empty message

Revision ID: 08b4812c3511
Revises: 817c25129274
Create Date: 2019-03-23 19:42:28.058811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08b4812c3511'
down_revision = '817c25129274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('name', sa.String(length=6000), nullable=False))
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', mysql.VARCHAR(length=6000), nullable=False))
    op.drop_column('admin', 'name')
    # ### end Alembic commands ###
