"""empty message

Revision ID: 0ad264c71cc3
Revises: a2c2da1920cc
Create Date: 2019-03-23 20:49:41.213082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad264c71cc3'
down_revision = 'a2c2da1920cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'timestamp')
    # ### end Alembic commands ###
