"""empty message

Revision ID: edbbd149b2f9
Revises: 08b4812c3511
Create Date: 2019-03-23 20:04:16.310313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edbbd149b2f9'
down_revision = '08b4812c3511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('name', sa.String(length=128), nullable=False))
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('admin', 'name')
    # ### end Alembic commands ###
